version: "3.9"
services:
  backend:
    build: ./Backend/App/ 
    volumes:
      - ./Backend/App/data:/App/data:rw
      - ./log/:/App/log/:rw
      - ./.env:/App/.env:ro
    ports:
      - ${SERVER_PORT}
  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./ClientApp/
      args:
        - SERVER_PORT=${SERVER_PORT}
        - PROXY_PORT=${PROXY_PORT}
        - PROXY_PORT_SSL=${PROXY_PORT_SSL}
    depends_on:
      - backend
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
      - "${PROXY_PORT_SSL}:${PROXY_PORT_SSL}"
