version: "3.9"
services:
  database_migrations:
    volumes:
      - ./Backend/App/data:/App/data:rw
    build:
      context: ./Backend/App/
      dockerfile: DockerfileDatabaseMigrations
  backend:
    build: 
      context: ./Backend/App/ 
      dockerfile: DockerfileMain
    volumes:
      - ./Backend/App/data:/App/data:rw
      - ./log/:/App/log/:rw
      - ./.env:/App/.env:ro
    ports:
      - ${SERVER_PORT}
    depends_on:
      database_migrations:
        condition: service_completed_successfully
  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./ClientApp/
      args:
        - SERVER_PORT=${SERVER_PORT}
        - PROXY_PORT=${PROXY_PORT}
        - PROXY_PORT_SSL=${PROXY_PORT_SSL}
    depends_on:
      - backend
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
      - "${PROXY_PORT_SSL}:${PROXY_PORT_SSL}"
