version: "3.9"
services:
  backend:
    build:
      dockerfile: ./DockerScripts/Main/Dockerfile
      context: .
    volumes:
      - ./database.db:/App/database.db:rw
    ports:
      - ${SERVER_PORT}
  frontend:
    build:
      context: ./DockerScripts/ReverseProxy/
      args:
        - SERVER_PORT=${SERVER_PORT}
        - PROXY_PORT=${PROXY_PORT}
        - PROXY_PORT_SSL=${PROXY_PORT_SSL}
    volumes:
      - ./ssl/my-site.crt:/etc/ssl/certs/my-site.crt
      - ./ssl/my-site.key:/etc/ssl/private/my-site.key
    depends_on:
      - backend
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
      - "${PROXY_PORT_SSL}:${PROXY_PORT_SSL}"
